ckpt: null # workdir/struct-gen-fs/last.ckpt
pretrained: null # workdir/nodiff-relpos-pade/last.ckpt # load weights from here first
validate: false # if true, only validate the model, don't train
logger:
    # set to true to log to neptune.ai
    neptune: true
    run_id: null  
    # please change "test" to something unique to your task
    project: openprot/diffusion
    # will log to workdir and neptune.ai with this name
    name: target-aligned-relpos
    # if not null, will duplicate stdout and stderr to workdir/{name}/{logfile}
    logfile: std.out
    # if null, will log every epoch, otherwise every this number of steps
    train_log_freq: 10
    val_log_freq: null 
    ckpt_freq: 1000000000
    save_freq: 1250
trainer:
    accelerator: auto
    devices: 1
    max_epochs: 1
    max_steps: 1000000
    enable_progress_bar: true
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    num_sanity_val_steps: 0
    gradient_clip_val: 1.0
    accumulate_grad_batches: 1
    val_check_interval: 5000
    check_val_every_n_epoch: 1
    logger: false

# custom args to OpenProtDataset and elsewhere
data: 
    num_workers: 16
    batch: 32
    crop: 256
    seed: 137

# These are the raw features which are expected to be supplied by the Datasets
# before they are TOKENIZED by the Tracks.
# We specify them and their shapes so that datasets can supply default values if missing
# for example, a structure dataset will not supply any dynamics information.
# We also need to set defaults for the "mask" and "noise" because not all Tasks will set them.
# -1 means this is the LEGNTH dim. 
features:
    # sequence feats
    seq_mask: [-1]
    seq_noise: [-1]
    # structure feats are unconventional
    # because they really mix 3 modalities
    atom37: [-1, 37, 3]
    atom37_mask: [-1, 37]
    trans_noise: [-1]
    rots_noise: [-1]
    # torsion_noise: [-1]

datasets:
    PDBDataset: 
        # path: /data/cb/scratch/datasets/pdb_npz
        path: /scratch/projects/cgai/openprot/data/pdb_npz
        cutoff: 2018-05-01
        clusters: /scratch/projects/cgai/openprot/data/pdb_clusters
        blacklist: /scratch/projects/cgai/openprot/cameo_pdb_blacklist.tsv
    AFDBDataset:
        #path: /data/cb/scratch/datasets/afdb_swissprot_v4/afdb_swissprot_v4
        path: /scratch/projects/cgai/openprot/data/afdb_rep_v4/afdb_rep_v4
        annotations: /scratch/projects/cgai/openprot/data/afdb_rep_v4.pkl.gz
        blacklist: null # /scratch/projects/cgai/openprot/cameo_afdb_blacklist.tsv
        plddt_thresh: null
        index: /scratch/projects/cgai/openprot/afdbreps_l-256_plddt_80.txt
        
    # UnirefDataset:
    #     #path: /data/cb/scratch/datasets/uniref50.fasta
    #     #index: /data/cb/scratch/datasets/uniref50.index
    #     path: /scratch/projects/cgai/openprot/data/uniref50.fasta
    #     index: /scratch/projects/cgai/openprot/data/uniref50.index
            
tasks:
    # SequenceGeneration:
    #     fraction: 0.1
    #     mask_rate: 0.15
    #     seed: 137
    #     datasets:
    #         UnirefDataset: 
    #             fraction: 1.0
    #             start: 0
    #             seed: 137
    StructureGeneration:
        fraction: 1.0
        beta: [1, 2]
        uniform_prob: 0.1
        max_noise_prob: 0.0
        seed: 137
        random_rot: true
        datasets:
            AFDBDataset:
                fraction: 1.0
                start: 0
                seed: 142
            PDBDataset:
                fraction: 0.0
                start: 0
                seed: 142
            
evals: 
    # StructurePredictionEval: 
    #     #path: /data/cb/scratch/datasets/afdb_swissprot_v4/afdb_swissprot_v4
    #     path: /scratch/projects/cgai/openprot/data/pdb_npz
    #     split: splits/cameo2022.csv
    #     diffusion: false
    #     augmented: false
    #     align: false
    #     demean: true
    struct_gen_ode:
        type: StructureGenerationEval
        num_samples: 10
        sample_length: 256
        nsteps: 200
        sde_weight: 0.0
        sched_type: 'log'
        temp_factor: 0.3
    struct_gen_sde:
        type: StructureGenerationEval
        num_samples: 10
        sample_length: 256
        nsteps: 200
        sched_type: 'log'
        sde_weight: 10.0
        temp_factor: 0.5
        
    

tracks:
    # register tracks here
    StructureTrack: 
        loss_weight: 1.0
        embed_rots: false
        readout_rots: false
        readout_rots_type: 'quat'
        readout_pairwise: false
        
        embed_trans: false
        readout_trans: false
        intermediate_loss: false
        
        rot_augment: 1
        embed_pairwise: false
        
        aligned_mse: true
        demean: true
        clamp_pade: false
        clamp_nape: true
        clamp_mse: false
        nape_cutoff: 15
        weighted_mse: true
        losses:
            #pade: 0.0
            #fape: 0.0
            #lddt: 0.0
            #distogram: 0.0
            mse: 1.0
            #nape: 0.0
        diffusion:
            type: GaussianFM
            prior_sigma: 15.0
            center_noise: false
            center_pos: true
            train_align: true
            inf_align: true
            prediction: "target"
    SequenceTrack:
        esm: null # esm2_3B # esm2_650M # esm2_8M_270K
        corrupt: mask
        mask_rate: 0.0
        loss_weight: 0.0

model: # custom args
    checkpoint: false
    dim: 1024
    pairwise_dim: 128
    heads: 16
    pairwise_heads: 4
    blocks: 15
    pair_block_interval: 1000
    ipa_block_interval: 1000
    pairwise_pos_emb: false
    
    ff_expand: 4
    position_bins: 32
    pair_ffn: true
    pair_values: false
    pair_ff_expand: 4
    tri_mul: true
    rope: true

    embed_trans_before_ipa: false
    detach_before_ipa: false
    zero_frames_before_ipa: false
    ### ipa args
    ipa_blocks: 8
    separate_ipa_blocks: true
    
    ipa_attn: false
    ipa_values: false
    no_qk_points: 4
    no_v_points: 8
    update_rots: false
    readout_rots: false
    rots_type: "vec"
    embed_rots: false
    ipa_frames: false
    frame_update: true
    relpos_attn: true
    relpos_values: true
    ipa_pair_values: false
    ipa_pair_bias: false
    detach_rots: true
    detach_trans: true
    update_x: true
    trunk_adaLN: true
    sm_adaLN: true
    augment_before_ipa: false

optimizer:
    type: AdamW
    lr: 1e-4
    scheduler: 
        total_steps: 1000000
        warmup_steps: 1000
        start_decay: 10000
        end_factor: 1.00
        