ckpt: null
pretrained: null
validate: true
logger:
  neptune: false
  run_id: null
  project: openprot/sequence
  name: noise-cos_rate-blosum62.csv_dist-beta_dim-1024
  logfile: null
  train_log_freq: 100
  val_log_freq: 10
  ckpt_freq: 100000
  save_freq: 1000
trainer:
  accelerator: auto
  devices: 1
  max_epochs: 1
  max_steps: 1000000
  enable_progress_bar: false
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  num_sanity_val_steps: 0
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  val_check_interval: 1000
  check_val_every_n_epoch: 1
  logger: true
data:
  num_workers: 8
  batch: 32
  crop: 512
  seed: 137
features:
  seq_mask:
  - -1
  seq_noise:
  - -1
datasets:
  uniref:
    type: UnirefDataset
    path: /scratch/projects/cgai/openprot/data/uniref50.fasta
    index: /scratch/projects/cgai/openprot/data/uniref50.index
tasks:
  SequenceDenoising:
    fraction: 1.0
    mask_rate: 0.15
    seed: 137
    datasets:
      uniref:
        fraction: 1.0
        start: 0
        seed: 137
    sampling: beta
    sampling_args:
    - 1
    - 2
evals:
  seq_gen:
    type: SequenceGeneration
    path: /scratch/projects/cgai/openprot/data/uniref50.fasta
    index: /scratch/projects/cgai/openprot/data/uniref50.index
    num_samples: 50
    n_steps: 200
    sample_length: 256
    inf: 1000000000
tracks:
  SequenceTrack:
    corrupt: discrete_fm
    mask_rate: 0.15
    loss_weight: 1.0
    rate_matrix_path: ./openprot/blosum62.csv
    noise_schedule: cos


model: # custom args
    checkpoint: true
    dim: 1024
    pairwise_dim: 128
    heads: 16
    pairwise_heads: 4
    blocks: 20
    
    # topology of the network
    pair_blocks:
        start: 0
        end: 0
        interval: 1
    struct_module: false
    sm_block_idx: 12
    
    pairwise_pos_emb: false
    
    ff_expand: 4
    position_bins: 32
    pair_ffn: true
    pair_values: false
    pair_bias: true
    pair_ff_expand: 4
    tri_mul: true
    rope: true

    ### ipa args

    zero_frames_before_ipa: true
    
    ipa_blocks: 8
    separate_ipa_blocks: false
    ipa_pair_values: false
    ipa_pair_bias: true
    detach_rots: true
    detach_trans: true
    trunk_adaLN: false
    sm_adaLN: false

optimizer:
  type: Adam
  lr: 3e-5
  scheduler:
    total_steps: 1000000
    warmup_steps: 1000
    start_decay: 10000
    end_factor: 1.0
