ckpt: null # eventually this will control resuming runs
validate: false # if true, only validate the model, don't train
logger:
    # set to true to log to neptune.ai
    neptune: false
    # please change "test" to something unique to your task
    project: openprot/structure
    # will log to workdir and neptune.ai with this name
    name: integrated
    # if not null, will duplicate stdout and stderr to workdir/{name}/{logfile}
    logfile: std.out
    # if null, will log every epoch, otherwise every this number of steps
    train_log_freq: 10
    val_log_freq: null 
    ckpt_freq: 100000
trainer:
    accelerator: auto
    devices: 1
    max_epochs: 1
    max_steps: 1000000
    enable_progress_bar: true
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    num_sanity_val_steps: 0
    gradient_clip_val: 1.0
    accumulate_grad_batches: 1
    val_check_interval: 1250
    check_val_every_n_epoch: 1
    logger: false

# custom args to OpenProtDataset and elsewhere
data: 
    num_workers: 8
    batch: 8
    crop: 256
    seed: 137

# These are the raw features which are expected to be supplied by the Datasets
# before they are TOKENIZED by the Tracks.
# We specify them and their shapes so that datasets can supply default values if missing
# for example, a structure dataset will not supply any dynamics information.
# We also need to set defaults for the "mask" and "noise" because not all Tasks will set them.
# -1 means this is the LEGNTH dim. 
features:
    # sequence feats
    seq_mask: [-1]
    seq_noise: [-1]
    # structure feats are unconventional
    # because they really mix 3 modalities
    atom37: [-1, 37, 3]
    atom37_mask: [-1, 37]
    trans_noise: [-1]
    rots_noise: [-1]
    # torsion_noise: [-1]

datasets:
    PDBDataset: 
        # path: /data/cb/scratch/datasets/pdb_npz
        path: /scratch/projects/cgai/openprot/data/pdb_npz
        cutoff: 2018-05-01
        clusters: /scratch/projects/cgai/openprot/data/pdb_clusters
    # AFDBDataset:
    #     #path: /data/cb/scratch/datasets/afdb_swissprot_v4/afdb_swissprot_v4
    #     path: /scratch/projects/cgai/openprot/data/afdb_swissprot_v4/afdb_swissprot_v4
    # UnirefDataset:
    #     #path: /data/cb/scratch/datasets/uniref50.fasta
    #     #index: /data/cb/scratch/datasets/uniref50.index
    #     path: /scratch/projects/cgai/openprot/data/uniref50.fasta
    #     index: /scratch/projects/cgai/openprot/data/uniref50.index
            
tasks:
    # SequenceGeneration:
    #     fraction: 0.1
    #     mask_rate: 0.15
    #     seed: 137
    #     datasets:
    #         UnirefDataset: 
    #             fraction: 1.0
    #             start: 0
    #             seed: 137
    StructurePrediction:
        fraction: 1.0
        seed: 137
        datasets:
            # AFDBDataset:
            #     fraction: 0.75
            #     start: 0
            #     seed: 142
            PDBDataset:
                fraction: 1.0
                start: 0
                seed: 142
            
evals:
    StructurePredictionEval: 
        #path: /data/cb/scratch/datasets/afdb_swissprot_v4/afdb_swissprot_v4
        path: /scratch/projects/cgai/openprot/data/pdb_npz
        split: splits/cameo2022.csv
        
    

tracks:
    # register tracks here
    StructureTrack: 
        pairwise: false
        # trunk: true
        # custom args for every track
        # embedder: 
        #     type: linear
        #     num_freqs: 50
        #     max_period: 400
        # decoder:
        #     type: linear
        #     max_period: 400
        #     scale: 1.0
        loss_weight: 1.0
        # logit_max_norm: null
        frames: false
        losses:
            # rmsd: 0.0
            # sinusoidal: 1.0
            pade: 0.0
            fape: 1.0
            distogram: 0.3
    SequenceTrack:
        esm: esm2_3B # esm2_650M # esm2_8M_270K
        corrupt: mask
        mask_rate: 0.0
        loss_weight: 0.0

model: # custom args
    in_norm: false
    dim: 1024
    blocks: 12
    heads: 16
    ff_expand: 4
    geometric_attn: [] #0,1,2,3,4,5,6,7,8,9,10,11]
    frame_update: [] #0,1,2,3,4,5,6,7,8,9,10,11]
    trunk:
        num_blocks: 12
        sequence_state_dim: 1024
        pairwise_state_dim: 128
        sequence_head_width: 32
        pairwise_head_width: 32
        position_bins: 32
        dropout: 0
        layer_drop: 0
        cpu_grad_checkpoint: false
        chunk_size: null
        structure_module:
            c_s: 384
            c_z: 128
            c_ipa: 16
            c_resnet: 128
            no_heads_ipa: 12
            no_qk_points: 4
            no_v_points: 8
            dropout_rate: 0.1
            no_blocks: 8
            no_transition_layers: 1
            no_resnet_blocks: 2
            no_angles: 7
            trans_scale_factor: 10
            epsilon: 1e-8
            inf: 1e5

optimizer:
    type: Adam
    lr: 5e-4
    scheduler: 
        total_steps: 1000000
        warmup_steps: 1000
        start_decay: 10000
        end_factor: 1.00
        