data_module:
    batch_size: 5

trainer:
    accelerator: auto
    max_epochs: 5
    enable_progress_bar: true
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    num_sanity_val_steps: 0
    gradient_clip_val: 1.0
    accumulate_grad_batches: 1
    val_check_interval: 200
    check_val_every_n_epoch: null
    logger: false

logger:
    neptune: true
    project: openprot/test
    train_log_freq: 100
    val_log_freq: null

model:

optimizer:
    type: Adam
    lr: 1e-4