ckpt: null # eventually this will control resuming runs
validate: false # if true, only validate the model, don't train
logger:
    # set to true to log to neptune.ai
    neptune: true
    # please change "test" to something unique to your task
    project: openprot/sequence
    # will log to workdir and neptune.ai with this name
    name: exp_200_steps
    # if not null, will duplicate stdout and stderr to workdir/{name}/{logfile}
    logfile: logfile # std.out 
    # if null, will log every epoch, otherwise every this number of steps
    train_log_freq: 100
    val_log_freq: 10
    ckpt_freq: 100000
    save_freq: 1000
trainer:
    accelerator: auto
    devices: 1
    max_epochs: 1
    max_steps: 1000000
    enable_progress_bar: false
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    num_sanity_val_steps: 0
    gradient_clip_val: 1.0
    accumulate_grad_batches: 1
    val_check_interval: 1000
    check_val_every_n_epoch: 1
    logger: true

# custom args to OpenProtDataset and elsewhere
data: 
    num_workers: 8
    batch: 32
    crop: 512
    seed: 137

# default features before tokenization
# each dataset sets MASK
# each task sets NOISE
features:
    # atom37: [37, 3]
    # atom37_mask: [37]
    seq_mask: [-1]
    seq_noise: [-1]
    # struct_mask: []
    # struct_noise: []

datasets:
    # PDBDataset: 
    #     path: /data/cb/scratch/datasets/pdb_npz
    # AFDBDataset:
    #     path: /data/cb/scratch/datasets/afdb_swissprot_v4/afdb_swissprot_v4
    UnirefDataset:
        path: /data/cb/scratch/datasets/uniref50.fasta
        index: /data/cb/scratch/share/openprot/uniref50.index
            
tasks:
    SequenceDenoising:
        fraction: 1.0
        mask_rate: 0.15
        seed: 137
        datasets:
            UnirefDataset: 
                fraction: 1.0
                start: 0
                seed: 137
        sampling: uniform
        sampling_args: []
            
evals:
    # PartialStructurePrediction: 
    #     path: /data/cb/scratch/datasets/afdb_swissprot_v4/afdb_swissprot_v4
    SequenceGeneration:
        path: /data/cb/scratch/datasets/uniref50.fasta
        index: /data/cb/scratch/share/openprot/uniref50.index
        num_samples: 50
        n_steps: 200
        sample_length: 256
        inf: 1000000000

tracks:
    # register tracks here
    # StructureTrack: 
    #     # custom args for every track
    #     embedder: 
    #         type: sinusoidal
    #         num_freqs: 50
    #         max_period: 400
    #     decoder:
    #         type: sinusoidal
    #         max_period: 400
    #         scale: 1.0
    #     loss_weight: 1.0
    #     logit_max_norm: 100
    #     losses: [rmsd, sinusoidal, pade]
    SequenceTrack:
        corrupt: discrete_fm
        mask_rate: 0.15
        loss_weight: 1.0
        rate_matrix_path: ./openprot/blosum62.csv
        noise_schedule: exp
        noise_min: 1
        noise_max: 15
        noise_k: 2

model: # custom args
    in_norm: false
    dim: 512
    blocks: 12
    heads: 8
    ff_expand: 4

optimizer:
    type: Adam
    lr: 3e-5
    scheduler: 
        total_steps: 1000000
        warmup_steps: 1000
        start_decay: 10000
        end_factor: 1.00
        
