name: openprot
channels:
  - pytorch
  - conda-forge
dependencies:
  - biopython=1.81
  - black=23.3.0
  - h5py=3.9.0
  - ipykernel=6.23.1
  - isort=5.12.0
  - jupyter=1.0.0
  - jupyterlab=4.0.1
  - lightning=2.0.7
  - matplotlib=3.7.2
  - neptune=1.10.4
  - numpy=1.25.1
  - omegaconf=2.3.0
  - pandas=1.5.3
  - pip=23.1.2
  - poetry=1.5.1
  - pre-commit=3.3.3
  - pylint=2.17.4
  - pytest=7.4.0
  - pytest-cov==3.0.0
  - python=3.11.3
  - pytorch=2.0.1
  - rdkit=2022.9.5
  - seaborn=0.12.2
  - scikit-learn=1.3.0
  - scipy=1.9.3
  - statsmodels=0.14.0
  - torchmetrics=0.11.4
  - torchvision=0.15.2
  - transformers=4.30.2
  - tqdm=4.65.0
  - pip:
    - huggingface-hub==0.23.4
    - ruff==0.5.2
