ckpt: null
validate: false
logger:
  neptune: true
  project: openprot/sequence
  name: noise-exp_rate-uniform.csv_dist-beta_dim-1024
  logfile: logfile
  train_log_freq: 100
  val_log_freq: 10
  ckpt_freq: 100000
  save_freq: 1000
trainer:
  accelerator: auto
  devices: 1
  max_epochs: 1
  max_steps: 1000000
  enable_progress_bar: false
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  num_sanity_val_steps: 0
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  val_check_interval: 1000
  check_val_every_n_epoch: 1
  logger: true
data:
  num_workers: 8
  batch: 32
  crop: 512
  seed: 137
features:
  seq_mask:
  - -1
  seq_noise:
  - -1
datasets:
  UnirefDataset:
    path: /data/cb/scratch/datasets/uniref50.fasta
    index: /data/cb/scratch/share/openprot/uniref50.index
tasks:
  SequenceDenoising:
    fraction: 1.0
    mask_rate: 0.15
    seed: 137
    datasets:
      UnirefDataset:
        fraction: 1.0
        start: 0
        seed: 137
    sampling: beta
    sampling_args:
    - 1
    - 2
evals:
  SequenceGeneration:
    path: /data/cb/scratch/datasets/uniref50.fasta
    index: /data/cb/scratch/share/openprot/uniref50.index
    num_samples: 50
    n_steps: 200
    sample_length: 256
    inf: 1000000000
tracks:
  SequenceTrack:
    corrupt: discrete_fm
    mask_rate: 0.15
    loss_weight: 1.0
    rate_matrix_path: ./openprot/uniform.csv
    noise_schedule: exp
model:
  in_norm: false
  dim: 1024
  blocks: 12
  heads: 8
  ff_expand: 4
optimizer:
  type: Adam
  lr: 3e-5
  scheduler:
    total_steps: 1000000
    warmup_steps: 1000
    start_decay: 10000
    end_factor: 1.0
