ckpt: null # workdir/1e3-relpos-384-bs4+afdb/last.ckpt # 
pretrained: null  #  load weights from here first
validate: false # if true, only validate the model, don't train
logger:
    # set to true to log to neptune.ai
    neptune: true
    run_id: null 
    # please change "test" to something unique to your task
    project: openprot/struct-merge
    # will log to workdir and neptune.ai with this name
    name: invfold-1e3-384-0.2 # invfold-1e3-relpos-256-bs4
    # if not null, will duplicate stdout and stderr to workdir/{name}/{logfile}
    logfile: std.out
    # if null, will log every epoch, otherwise every this number of steps
    train_log_freq: 100
    val_log_freq: null 
    ckpt_freq: 50000000000
    save_freq: 5000
trainer:
    accelerator: auto
    devices: 1
    max_epochs: 1
    max_steps: 1000000
    enable_progress_bar: true
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    num_sanity_val_steps: 0
    gradient_clip_val: 1.0
    accumulate_grad_batches: 1
    val_check_interval: 20000
    check_val_every_n_epoch: 1
    logger: false

# custom args to OpenProtDataset and elsewhere
data: 
    num_workers: 8
    batch: 32
    crop: 256
    seed: 137

# These are the raw features which are expected to be supplied by the Datasets
# before they are TOKENIZED by the Tracks.
# We specify them and their shapes so that datasets can supply default values if missing
# for example, a structure dataset will not supply any dynamics information.
# We also need to set defaults for the "mask" and "noise" because not all Tasks will set them.
# -1 means this is the LEGNTH dim. 
features:
    # sequence feats
    seq_mask: [-1]
    seq_noise: [-1]
    # structure feats are unconventional
    # because they really mix 3 modalities
    atom37: [-1, 37, 3]
    atom37_mask: [-1, 37]
    trans_noise: [-1]
    rots_noise: [-1]
    # torsion_noise: [-1]

datasets:
    pdb:
        type: PDBDataset
        path: /scratch/projects/cgai/openprot/data/pdb_npz
        cutoff: 2018-05-01
        clusters: /scratch/projects/cgai/openprot/data/pdb_clusters
        blacklist: /scratch/projects/cgai/openprot/cameo_pdb_blacklist.tsv
    afdb_genie:
        type: AFDBDataset
        path: /scratch/projects/cgai/openprot/data/afdb_rep_v4/afdb_rep_v4
        annotations: /scratch/projects/cgai/openprot/data/afdb_rep_v4.pkl.gz
        blacklist: null 
        plddt_thresh: null 
        index: /scratch/projects/cgai/openprot/afdbreps_l-256_plddt_80.txt
    afdb:
        type: AFDBDataset
        path: /scratch/projects/cgai/openprot/data/afdb_rep_v4/afdb_rep_v4
        annotations: /scratch/projects/cgai/openprot/data/afdb_rep_v4.pkl.gz
        blacklist: /scratch/projects/cgai/openprot/cameo_afdb_blacklist.tsv
        plddt_thresh: 80
        index: null
    uniref:
        type: UnirefDataset
        path: /scratch/projects/cgai/openprot/data/uniref50.fasta
        index: /scratch/projects/cgai/openprot/data/uniref50.index  

tasks:
    InverseFolding:
        fraction: 1.0
        beta: [1, 2]
        uniform_prob: 1.0
        seed: 137
        random_rot: true
        sigma: 0.2
        datasets:
            pdb:
                fraction: 0.25
                start: 0
                seed: 37
            afdb:
                fraction: 0.75
                start: 0
                seed: 37  
    # SequenceUnmasking: # make it impossible to predict X
    #     fraction: 0.0
    #     # beta: [1, 2]
    #     # uniform_prob: 0.0
    #     beta: [3, 9]
    #     uniform_prob: 0.2 
    #     seed: 137
    #     datasets:
    #         uniref:
    #             fraction: 1.0
    #             start: 0
    #             seed: 678
    # SequenceDenoising:
    #     fraction: 0.0
    #     seed: 137
    #     datasets:
    #         uniref:
    #             fraction: 1.0
    #             start: 0
    #             seed: 137
    #     sampling: beta
    #     sampling_args: [1, 2]
    # StructurePrediction:
    #     fraction: 0.0
    #     beta: [1, 2]
    #     uniform_prob: 0.0
    #     max_noise_prob: 1.0
    #     seed: 137
    #     random_rot: true
    #     datasets:
    #         afdb:
    #             fraction: 0.75
    #             start: 0
    #             seed: 142
    #         pdb:
    #             fraction: 0.25
    #             start: 0
    #             seed: 142
    # StructureGeneration:
    #     fraction: 0.0
    #     beta: [1, 2]
    #     uniform_prob: 0.5
    #     seed: 137
    #     random_rot: true
    #     datasets:
    #         afdb_genie:
    #             fraction: 1.0
    #             start: 0
    #             seed: 142
            
evals: 
    # cameo22:
    #     type: StructurePredictionEval
    #     path: /scratch/projects/cgai/openprot/data/pdb_npz
    #     split: splits/cameo2022.csv
    #     diffusion: false
    #     augmented: false
    #     align: false
    #     demean: true
    # struct_gen_sde_0.5:
    #     type: StructureGenerationEval
    #     num_samples: 100
    #     sample_length: 128
    #     nsteps: 200
    #     sched_type: 'log'
    #     sde_weight: 10.0
    #     temp_factor: 0.5
    #     sde_cutoff_time: 0.0
    #     sde_cutoff_width: 0.00001
    #     run_designability: true
    # struct_gen_sde_0.7:
    #     type: StructureGenerationEval
    #     num_samples: 100
    #     sample_length: 128
    #     nsteps: 200
    #     sched_type: 'log'
    #     sde_weight: 10.0
    #     temp_factor: 0.7
    #     sde_cutoff_time: 0.0
    #     sde_cutoff_width: 0.00001
    #     run_designability: true
    # struct_gen_sde_1.0:
    #     type: StructureGenerationEval
    #     num_samples: 100
    #     sample_length: 128
    #     nsteps: 200
    #     sched_type: 'log'
    #     sde_weight: 10.0
    #     temp_factor: 1.0
    #     sde_cutoff_time: 0.0
    #     sde_cutoff_width: 0.00001
    #     run_designability: true
    # seq_gen_dplm: 
    #     type: SequenceGenerationEval
    #     num_samples: 100
    #     sample_length: 128
    #     steps: 128
    #     temp: 0.7
    cameo22_invfold:
        type: InverseFoldingEval
        path: ./cameo
        split: splits/cameo2022.csv
        temp: 0.1
        sigma: 0.2
        
        # order: random
tracks:
    # register tracks here
    StructureTrack: 
        loss_weight: 0.0
        readout_pairwise: true
        embed_trans: null
        t_emb_p: 7
        t_emb_max: 2000
        # trunk or sm
        readout_trans: trunk
        postcondition: true
        int_loss_weight: 0.5
        postcond_before_relpos: true
        embed_pairwise: false
        losses:
            lddt: 1.0
            distogram: 0.3
            mse: 0.225
        diffusion:
            type: EDMDiffusion
            data_sigma: 15
            aligned_loss: true
    SequenceTrack:
        esm: null # esm2_3B # esm2_650M # esm2_8M_270K
        loss_weight: 1.0 
        embed_t: false
        loss_reweight: var

model: # custom args
    checkpoint: true
    dim: 384 # 640
    pairwise_dim: 128
    heads: 4 # 20
    pairwise_heads: 4
    blocks: 12 # 30

    relpos: true
    # topology of the network
    pair_blocks:
        start: 0
        end: 0
        interval: 1
    struct_module: false
    sm_block_idx: 12
    
    pairwise_pos_emb: false
    block_pair_bias: false
    ff_expand: 4
    position_bins: 32
    pair_ffn: true
    pair_values: false
    pair_bias: true
    pair_ff_expand: 4
    tri_mul: true
    rope: false
    custom_rope: true

    ### ipa args
    readout_trans_before_sm: false
    zero_frames_before_ipa: true
    
    ipa_blocks: 8
    separate_ipa_blocks: false
    ipa_pair_values: false
    ipa_pair_bias: true
    detach_rots: true
    detach_trans: true
    trunk_adaLN: false
    sm_adaLN: false


optimizer:
    type: AdamW
    lr: 1e-3
    betas: [0.9, 0.98]
    eps: 1e-8
    weight_decay: 0.01
    fused: true
    scheduler: 
        total_steps: 1000000
        warmup_steps: 2000
        start_decay: 10000
        end_factor: 1.00
        