ckpt: 
pretrained:   #  load weights from here first
validate: false # if true, only validate the model, don't train
logger:
    # set to true to log to neptune.ai
    neptune: true
    run_id: 
    # please change "test" to something unique to your task
    project: openprot/struct-merge
    # will log to workdir and neptune.ai with this name
    name: seq-gen-new 
    # if not null, will duplicate stdout and stderr to workdir/{name}/{logfile}
    logfile: std.out
    # if null, will log every epoch, otherwise every this number of steps
    train_log_freq: 100
    val_log_freq: null 
    ckpt_freq: 50000000000
    save_freq: 1000
trainer:
    accelerator: auto
    devices: 8
    max_epochs: 1
    max_steps: 1000000
    enable_progress_bar: true
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    num_sanity_val_steps: 0
    gradient_clip_val: 1.0
    accumulate_grad_batches: 1
    val_check_interval: 10000
    check_val_every_n_epoch: 1
    logger: false
    precision: 16-mixed

# custom args to OpenProtDataset and elsewhere
data: 
    num_workers: 8
    buffer: 1000
    max_sq_toks: null # 400000
    max_toks: 8192
    batch: null
    crop: 1024
    seed: 137


# These are the raw features which are expected to be supplied by the Datasets
# before they are TOKENIZED by the Tracks.
# We specify them and their shapes so that datasets can supply default values if missing
# for example, a structure dataset will not supply any dynamics information.
# We also need to set defaults for the "mask" and "noise" because not all Tasks will set them.
# -1 means this is the LEGNTH dim. 
features:
    # sequence feats
    atom_num: [-1] # ligands only
    mol_type: [-1] # default 0 = protein
    seq_mask: [-1]
    seq_noise: [-1]
    seq_weight: [-1]
    struct: [-1, 3]
    struct_mask: [-1]
    struct_noise: [-1]
    struct_weight: [-1]
    ref_conf: [-1, 3]
    residx: [-1]
    chain: [-1]
    
    
datasets:
    uniref:
        type: UnirefDataset
        path: /data/cb/scratch/datasets/uniref50.fasta
        index: /data/cb/scratch/datasets/uniref50.idx.npy  

tasks:
    SequenceUnmasking: 
        fraction: 1.0
        weight: 1.0
        beta: [3, 9]
        uniform_prob: 1.0
        seed: 137
        datasets:
            uniref:
                fraction: 1.0
                start: 0
                seed: 40

            
            
evals: 
    seq_gen_dplm: 
        type: SequenceGenerationEval
        num_samples: 100
        sample_length: 300
        batch: 100
        steps: 300
        temp_start: 0.5
        temp_end: 0.5
        strategy: dplm
        logits: gumbel
        remask: 0.0
        topk_temp: 0.0
        replace_unmasked: false
        adjust_unmasked: false
        allow_mutation: false
        
        

tracks:
    SequenceTrack:
        esm: # esm2_3B # esm2_650M # esm2_8M_270K
        loss_weight: 1.0 
        mask_rate: 1.0
        rand_rate: 0.0
        esm_lm_head: true
        sup_all: false
        tied_weights: false
        embed_t: false
        readout: trunk
        init: 
        all_atom: false


model: # custom args
    dplm_ckpt: null
    multiflow: false
    multiflow_cfg: multiflow_config.yaml
    multiflow_ckpt: null # ./weights/last.ckpt
    ema: false
    checkpoint: false
    dim: 512
    pairwise_dim: 128
    heads: 16
    pairwise_heads: 4
    blocks: 30
    dropout: 0.1
    token_dropout: 0.1
    
    trunk_relpos: false
    trunk_frame_update: false
    trunk_update_rots: false
    trunk_ipa_frames: false
    embed_rots: false
    trunk_ipa: false
    
    pairwise_pos_emb: false
    
    ff_expand: 4
    position_bins: 32
    # whether non-pair blocks still have pair bias
    block_pair_bias: false 
    block_pair_values: false
    tri_mul: false
    rope: false
    custom_rope: true

    ## adaLN args
    trunk_adaLN: false
    
    



optimizer:
    type: AdamW
    lr: 3e-5
    # betas: [0.9, 0.98]
    # eps: 1e-8
    # weight_decay: 0.01
    # fused: true
    scheduler: 
        total_steps: 1000000
        warmup_steps: 2000
        start_decay: 10000
        end_factor: 1.00