ckpt: workdir/codesign-mixed4/last.ckpt
pretrained: null  #  load weights from here first
validate: true # if true, only validate the model, don't train
logger:
    # set to true to log to neptune.ai
    neptune: false
    run_id: 
    # please change "test" to something unique to your task
    project: openprot/struct-merge
    # will log to workdir and neptune.ai with this name
    name: codesign-mixed4
    # if not null, will duplicate stdout and stderr to workdir/{name}/{logfile}
    logfile: # std.out
    # if null, will log every epoch, otherwise every this number of steps
    train_log_freq: 100
    val_log_freq: null 
    ckpt_freq: 50000000000
    save_freq: 1000
trainer:
    accelerator: auto
    devices: 8
    max_epochs: 1
    max_steps: 1000000
    enable_progress_bar: false
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    num_sanity_val_steps: 0
    gradient_clip_val: 1.0
    accumulate_grad_batches: 1
    val_check_interval: 10000
    check_val_every_n_epoch: 1
    logger: false
    precision: 16-mixed

# custom args to OpenProtDataset and elsewhere
data: 
    num_workers: 8
    buffer: 1000
    max_sq_toks: null # 400000
    max_toks: 4096
    batch: null
    crop: 384
    seed: 137

# These are the raw features which are expected to be supplied by the Datasets
# before they are TOKENIZED by the Tracks.
# We specify them and their shapes so that datasets can supply default values if missing
# for example, a structure dataset will not supply any dynamics information.
# We also need to set defaults for the "mask" and "noise" because not all Tasks will set them.
# -1 means this is the LEGNTH dim. 
features:
    # sequence feats
    seq_mask: [-1]
    seq_noise: [-1]
    seq_weight: [-1]
    # structure feats are unconventional
    # because they really mix 3 modalities
    atom37: [-1, 37, 3]
    atom37_mask: [-1, 37]
    struct_noise: [-1]
    struct_weight: [-1]
    residx: [-1]
    
    
datasets:
    pdb:
        type: PDBDataset
        path: /data/cb/scratch/datasets/pdb_npz
        cutoff: 2018-05-01
        clusters: /data/cb/scratch/datasets/pdb_npz/pdb_clusters
        blacklist: null 
        struct_mask: false
    afdb_genie:
        type: AFDBDataset
        path: /data/cb/scratch/datasets/afdb_rep_v4/afdb_rep_v4
        annotations: /data/cb/scratch/datasets/afdb_rep_v4.pkl.gz
        blacklist: null 
        plddt_thresh: null 
        index: /data/cb/scratch/datasets/afdbreps_l-256_plddt_80.txt
    multiflow: 
        type: MultiflowDataset
        config_path: multiflow_config.yaml 
tasks:
        
    StructureGeneration:
        rescale_time: ${tracks.StructureTrack.rescale_time}
        sched_p: ${tracks.StructureTrack.t_emb_p}
        sigma_max: ${tracks.StructureTrack.t_emb_max}
        sigma_min: ${tracks.StructureTrack.t_emb_min}
        rots: false

        fraction: 0.5
        weight: 1.0
        struct_weight: 1.0
        struct_beta: [1, 2]
        struct_max_noise_prob: 0.0
        struct_uniform_prob: 0.5
        
        seed: 137
        random_rot: true
        
        datasets:
            afdb_genie:
                fraction: 0.75
                start: 0
                seed: 42
            pdb:
                fraction: 0.25
                start: 0
                seed: 42

    InverseFolding:
        fraction: 0.5
        weight: 1.0
        beta: [1, 2]
        uniform_prob: 1.0
        seed: 137
        random_rot: true
        sigma: ${tracks.StructureTrack.t_emb_min}
        reweight: false
        datasets:
            pdb:
                fraction: 0.25
                start: 0
                seed: 37
            afdb_genie:
                fraction: 0.75
                start: 0
                seed: 38
            
evals: 
    codesign_skew+1:
        type: CodesignEval
        num_samples: 100
        batch: 100
        sample_length: 128
        steps: 400
        skew: 1
        struct:
            rescale_time: ${tracks.StructureTrack.rescale_time}
            sched_p: ${tracks.StructureTrack.t_emb_p}
            sigma_max: ${tracks.StructureTrack.t_emb_max}
            sigma_min: ${tracks.StructureTrack.t_emb_min}
            type: ${tracks.StructureTrack.diffusion.type}
            temp_factor: 0.5
            sde_weight: 3.0
            data_sigma: ${tracks.StructureTrack.diffusion.data_sigma}
            sched: edm
            max_t: 0.95
        seq:
            temp: 0.1
            strategy: random
            # noise: 20
            logits: standard
            adjust_unmasked: false
            # replace_unmasked: false
        run_designability: true
        run_pmpnn_designability: false
        run_diversity: true
        run_secondary: true

    # struct_gen_sde_0.5:
    #     type: StructureGenerationEval
    #     num_samples: 100
    #     batch: 100
    #     sample_length: 128
    #     steps: 200
    #     struct:
    #         rescale_time: ${tracks.StructureTrack.rescale_time}
    #         sched_p: ${tracks.StructureTrack.t_emb_p}
    #         sigma_max: ${tracks.StructureTrack.t_emb_max}
    #         sigma_min: ${tracks.StructureTrack.t_emb_min}
    #         type: ${tracks.StructureTrack.diffusion.type}
    #         temp_factor: 0.5
    #         sde_weight: 3.0
    #         data_sigma: ${tracks.StructureTrack.diffusion.data_sigma}
    #         sched: edm
    #         max_t: 0.95
    #     run_designability: false
    #     run_diversity: false

    # cameo22_invfold:
    #     type: InverseFoldingEval
    #     path: ./cameo
    #     split: splits/cameo2022.csv
    #     temp: 0.1
    #     sigma: ${tasks.InverseFolding.sigma}
    #     batch: 1
    #     steps: 
    #     limit: 16
    #     logits: standard
    #     strategy: random
    #     adjust_unmasked: false

    # codesign_invfold: 
    #     type: InverseFoldingEval
    #     # inv fold model gets 34%, codesign-mixed-4 gets 22%
    #     path: workdir/codesign-mixed4/eval_step0/struct_gen_sde_0.5
    #     path: workdir/codesign-mixed4/eval_step0/codesign_skew+1
    #     split: 
    #     temp: 0.1
    #     sigma: ${tasks.InverseFolding.sigma}
    #     batch: 100
    #     steps: 
    #     limit: 100
    #     logits: standard
    #     strategy: random
    #     # topk_temp: 0.0
    #     # noise: 20
    #     adjust_unmasked: false
    #     # replace_unmasked: false
    #     # allow_mutation: false
tracks:
    # register tracks here
    StructureTrack: 
        loss_weight: 1.0
        embed_trans: true
        embed_pairwise: false
        readout_trans: trunk
        copy_trans: false
        readout_pairwise: false
        postcondition: true
        int_loss_weight: 0.5
        embed_sigma: false
        rots: false
        clip_t: 0.0
        rescale_time: true
        t_emb_p: 7
        t_emb_max: 160
        t_emb_min: 0.05
        readout_adaLN: false

        
        losses:
            lddt: 1.0
            # distogram: 0.3
            mse: 0.225
        diffusion:
            type: EDMDiffusion
            data_sigma: 15
            aligned_loss: true
            train_align: false
            rescale_time: ${tracks.StructureTrack.rescale_time}
        
    SequenceTrack:
        esm: null # esm2_3B # esm2_650M # esm2_8M_270K
        loss_weight: 1.0 
        mask_rate: 1.0
        rand_rate: 0.0
        esm_lm_head: true
        sup_all: false
        tied_weights: false
        embed_t: false
        readout: trunk
        init: 


model: # custom args
    dplm_ckpt: null
    multiflow: false
    multiflow_cfg: multiflow_config.yaml
    multiflow_ckpt: null # ./weights/last.ckpt
    ema: false
    checkpoint: false
    dim: 512
    pairwise_dim: 128
    heads: 16
    pairwise_heads: 4
    blocks: 30
    dropout: 0.0
    token_dropout: 0.0

    
    trunk_relpos_params: [32, 0.1, 10]
    
    # topology of the network
    pair_blocks:
        start: 0
        end: 0
        interval: 4
    relpos_blocks:
        start: 0
        end: 0
        interval: 4
    update_blocks:
        start: 0
        end: 0
        interval: 4
    
    trunk_relpos: false
    trunk_frame_update: false
    trunk_update_rots: false
    trunk_ipa_frames: false
    embed_rots: false
    trunk_ipa: false
    
    pairwise_pos_emb: false
    
    ff_expand: 4
    position_bins: 32
    # whether non-pair blocks still have pair bias
    block_pair_bias: false 
    block_pair_values: false
    pair_ffn: true
    pair_values: true
    pair_bias: true
    pair_ff_expand: 4
    tri_mul: false
    rope: false
    custom_rope: true
    

    ### struct module args
    struct_module: false
    sm_relpos: [32, 1, 100]
    move_x_to_xcond: true
    readout_trans_before_sm: false
    zero_frames_before_ipa: true
    ipa_blocks: 8
    separate_ipa_blocks: true
    ipa_pair_values: false
    ipa_pair_bias: false
    detach_trans: true    
    ipa_relpos: true
    ipa_nipa: false
    ipa_rope: false
    ipa_frame_update: true
    zero_x_before_ipa: false
    trans_rescale: false

    ## adaLN args
    trunk_adaLN: true
    sm_adaLN: true
    readout_adaLN: true
    
optimizer:
    type: AdamW
    lr: 1e-4
    # betas: [0.9, 0.98]
    # eps: 1e-8
    # weight_decay: 0.01
    # fused: true
    scheduler: 
        total_steps: 1000000
        warmup_steps: 1000
        start_decay: 10000
        end_factor: 1.00
