ckpt: workdir/codesign-test2/last.ckpt
pretrained: null  #  load weights from here first
validate: false # if true, only validate the model, don't train
logger:
    # set to true to log to neptune.ai
    neptune: true
    run_id: STRUC1-450
    # please change "test" to something unique to your task
    project: openprot/struct-merge
    # will log to workdir and neptune.ai with this name
    name: codesign-test2 # merge-std-struct-gen-linear 
    # if not null, will duplicate stdout and stderr to workdir/{name}/{logfile}
    logfile: std.out
    # if null, will log every epoch, otherwise every this number of steps
    train_log_freq: 100
    val_log_freq: null 
    ckpt_freq: 50000000000
    save_freq: 5000
trainer:
    accelerator: auto
    devices: 1
    max_epochs: 1
    max_steps: 1000000
    enable_progress_bar: true
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    num_sanity_val_steps: 0
    gradient_clip_val: 1.0
    accumulate_grad_batches: 1
    val_check_interval: 10000
    check_val_every_n_epoch: 1
    logger: false
    precision: 16-mixed

# custom args to OpenProtDataset and elsewhere
data: 
    num_workers: 32
    buffer: 1000
    max_toks: 8192
    batch: null
    crop: 512 
    seed: 137

# These are the raw features which are expected to be supplied by the Datasets
# before they are TOKENIZED by the Tracks.
# We specify them and their shapes so that datasets can supply default values if missing
# for example, a structure dataset will not supply any dynamics information.
# We also need to set defaults for the "mask" and "noise" because not all Tasks will set them.
# -1 means this is the LEGNTH dim. 
features:
    # sequence feats
    seq_mask: [-1]
    seq_noise: [-1]
    seq_weight: [-1]
    # structure feats are unconventional
    # because they really mix 3 modalities
    atom37: [-1, 37, 3]
    atom37_mask: [-1, 37]
    struct_noise: [-1]
    struct_weight: [-1]
    
    
datasets:
    pdb:
        type: PDBDataset
        path: /scratch/projects/cgai/openprot/data/pdb_npz
        cutoff: 2018-05-01
        clusters: /scratch/projects/cgai/openprot/data/pdb_clusters
        blacklist: /scratch/projects/cgai/openprot/cameo_pdb_blacklist.tsv
    afdb_genie:
        type: AFDBDataset
        path: /scratch/projects/cgai/openprot/data/afdb_rep_v4/afdb_rep_v4
        annotations: /scratch/projects/cgai/openprot/data/afdb_rep_v4.pkl.gz
        blacklist: null 
        plddt_thresh: null 
        index: /scratch/projects/cgai/openprot/afdbreps_l-256_plddt_80.txt
    synthetic: 
        type: MultiflowDataset
        path: /scratch/projects/cgai/openprot/processed_synthetic
        
tasks:
    Codesign:
        fraction: 1.0
        weight: 1.0
        
        seq_weight: 1.0
        seq_beta: [1, 2]
        seq_max_noise_prob: 0.0
        seq_uniform_prob: 1.0
        
        struct_weight: 1.0
        struct_beta: [1, 2]
        struct_max_noise_prob: 0.0
        struct_uniform_prob: 0.5
        
        seed: 137
        random_rot: true
        sched_p: ${tracks.StructureTrack.t_emb_p}
        sigma_max: ${tracks.StructureTrack.t_emb_max}
        sigma_min: ${tracks.StructureTrack.t_emb_min}
        
        datasets:
            synthetic:
                fraction: 0.25
                start: 0
                seed: 41
            pdb:
                fraction: 0.75
                start: 0
                seed: 42
            
evals: 
    # codesign_dplm:
    #     type: CodesignEval
    #     num_samples: 100
    #     batch: 100
    #     sample_length: 128
    #     steps: 200
    #     sched_p: ${tracks.StructureTrack.t_emb_p}
    #     sigma_max: ${tracks.StructureTrack.t_emb_max}
    #     sigma_min: ${tracks.StructureTrack.t_emb_min}
    #     struct:
    #         temp_factor: 0.5
    #     seq:
    #         temp: 0.1
    #         strategy: dplm
    #         logits: gumbel
    #         remask: 0.0
    #         topk_temp: 0.0
    #         allow_mutation: false
    #         adjust_unmasked: false
    #         replace_unmasked: false
    #     run_designability: true
    codesign_random:
        type: CodesignEval
        num_samples: 100
        batch: 100
        sample_length: 128
        steps: 200
        sched_p: ${tracks.StructureTrack.t_emb_p}
        sigma_max: ${tracks.StructureTrack.t_emb_max}
        sigma_min: ${tracks.StructureTrack.t_emb_min}
        struct:
            temp_factor: 0.5
        seq:
            temp: 0.1
            strategy: purity
            noise: 20
            logits: standard
            adjust_unmasked: false
            replace_unmasked: false
        run_designability: true

        
        # order: random
tracks:
    # register tracks here
    StructureTrack: 
        loss_weight: 1.0
        embed_trans: true
        embed_pairwise: false
        readout_trans: false
        readout_pairwise: false
        postcondition: true
        int_loss_weight: 0.5
        t_emb_p: 7
        t_emb_max: 160
        t_emb_min: 0.05
        embed_sigma: false
        
        losses:
            lddt: 1.0
            # distogram: 0.3
            mse: 0.225
        diffusion:
            type: EDMDiffusion
            data_sigma: 15
            aligned_loss: true
    SequenceTrack:
        esm: null # esm2_3B # esm2_650M # esm2_8M_270K
        loss_weight: 1.0 
        mask_rate: 1.0
        rand_rate: 0.0
        esm_lm_head: false
        embed_t: false


model: # custom args
    dplm_ckpt: null
    checkpoint: false
    dim: 512
    pairwise_dim: 128
    heads: 16
    pairwise_heads: 4
    blocks: 30
    dropout: 0.0
    token_dropout: 0.0

    
    trunk_relpos: [32, 1, 1000]
    sm_relpos: [32, 1, 100]
    # topology of the network
    pair_blocks:
        start: 0
        end: 0
        interval: 1
    relpos_blocks:
        start: 0
        end: 0
        interval: 4
    struct_module: true
    
    pairwise_pos_emb: false
    block_pair_bias: false
    ff_expand: 4
    position_bins: 32
    pair_ffn: true
    pair_values: false
    pair_bias: true
    pair_ff_expand: 4
    tri_mul: false
    rope: false
    custom_rope: true
    

    ### ipa args
    readout_trans_before_sm: false
    zero_frames_before_ipa: true
    
    ipa_blocks: 8
    separate_ipa_blocks: false
    ipa_pair_values: false
    ipa_pair_bias: false
    detach_trans: true
    trunk_adaLN: true
    sm_adaLN: true
    readout_adaLN: true
    
    move_x_to_xcond: true
    ipa_relpos: true
    ipa_nipa: false
    ipa_rope: false
    ipa_frame_update: true
    zero_x_before_ipa: false


optimizer:
    type: AdamW
    lr: 1e-4
    # betas: [0.9, 0.98]
    # eps: 1e-8
    # weight_decay: 0.01
    # fused: true
    scheduler: 
        total_steps: 1000000
        warmup_steps: 1000
        start_decay: 10000
        end_factor: 1.00
