ckpt: null # workdir/struct-pred-trimul/last.ckpt # 
pretrained: null # workdir/trimul-vanilla-disto/last.ckpt # workdir/nodiff-relpos-pade/last.ckpt # load weights from here first
validate: false # if true, only validate the model, don't train
logger:
    # set to true to log to neptune.ai
    neptune: true
    run_id: null  
    # please change "test" to something unique to your task
    project: openprot/struct-merge
    # will log to workdir and neptune.ai with this name
    name: struct-pred-trimul-postcond
    # if not null, will duplicate stdout and stderr to workdir/{name}/{logfile}
    logfile: std.out
    # if null, will log every epoch, otherwise every this number of steps
    train_log_freq: 10
    val_log_freq: null 
    ckpt_freq: 1000000000
    save_freq: 1250
trainer:
    accelerator: auto
    devices: 1
    max_epochs: 1
    max_steps: 1000000
    enable_progress_bar: true
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    num_sanity_val_steps: 0
    gradient_clip_val: 1.0
    accumulate_grad_batches: 1
    val_check_interval: 1250
    check_val_every_n_epoch: 1
    logger: false

# custom args to OpenProtDataset and elsewhere
data: 
    num_workers: 16
    batch: 8
    crop: 256
    seed: 137

# These are the raw features which are expected to be supplied by the Datasets
# before they are TOKENIZED by the Tracks.
# We specify them and their shapes so that datasets can supply default values if missing
# for example, a structure dataset will not supply any dynamics information.
# We also need to set defaults for the "mask" and "noise" because not all Tasks will set them.
# -1 means this is the LEGNTH dim. 
features:
    # sequence feats
    seq_mask: [-1]
    seq_noise: [-1]
    # structure feats are unconventional
    # because they really mix 3 modalities
    atom37: [-1, 37, 3]
    atom37_mask: [-1, 37]
    trans_noise: [-1]
    rots_noise: [-1]
    # torsion_noise: [-1]

datasets:
    pdb:
        type: PDBDataset
        path: /scratch/projects/cgai/openprot/data/pdb_npz
        cutoff: 2018-05-01
        clusters: /scratch/projects/cgai/openprot/data/pdb_clusters
        blacklist: /scratch/projects/cgai/openprot/cameo_pdb_blacklist.tsv
    afdb:
        type: AFDBDataset
        path: /scratch/projects/cgai/openprot/data/afdb_rep_v4/afdb_rep_v4
        annotations: /scratch/projects/cgai/openprot/data/afdb_rep_v4.pkl.gz
        blacklist: /scratch/projects/cgai/openprot/cameo_afdb_blacklist.tsv
        plddt_thresh: 70
        index: null # tmp/afdbreps_l-256_plddt_80.txt
        
tasks:
    StructurePrediction:
        fraction: 1.0
        beta: [1, 2]
        uniform_prob: 0.5
        max_noise_prob: 0.5
        seed: 137
        random_rot: true
        datasets:
            afdb:
                fraction: 0.75
                start: 0
                seed: 142
            pdb:
                fraction: 0.25
                start: 0
                seed: 142
            
evals: 
    cameo22:
        type: StructurePredictionEval
        path: /scratch/projects/cgai/openprot/data/pdb_npz
        split: splits/cameo2022.csv
        diffusion: false
        trans_as_pos: false
    # cameo22_diff:
    #     type: StructurePredictionEval
    #     path: /scratch/projects/cgai/openprot/data/pdb_npz
    #     split: splits/cameo2022.csv
    #     diffusion: true
    #     nsteps: 20
    #     temp_factor: 0.5
        

tracks:
    # register tracks here
    StructureTrack: 
        loss_weight: 1.0
        readout_pairwise: true
        embed_trans: edm
        # trunk or sm
        readout_trans: null
        postcondition: true
        int_loss_weight: 0.5
        postcond_before_relpos: true
        embed_pairwise: false
        losses:
            lddt: 1.0
            distogram: 0.3
            mse: 0.225
        diffusion:
            # type: GaussianFM
            # prior_sigma: 15.0
            # center_noise: false
            # center_pos: true
            # train_align: true
            # inf_align: true
            # prediction: "target"
            type: EDMDiffusion
            sched_p: 7
            data_sigma: 15
            sigma_max: 2000
            sigma_min: 0.05
            aligned_loss: true
    SequenceTrack:
        esm: esm2_3B # esm2_650M # esm2_8M_270K
        corrupt: mask
        mask_rate: 0.0
        loss_weight: 0.0

model: # custom args
    checkpoint: true
    dim: 1024
    pairwise_dim: 128
    heads: 16
    pairwise_heads: 4
    blocks: 12
    
    block_pair_bias: true
    # topology of the network
    pair_blocks:
        start: 0
        end: 12
        interval: 1
    struct_module: true
    pairwise_pos_emb: true
    
    
    ff_expand: 4
    position_bins: 32
    pair_ffn: true
    pair_bias: true
    pair_values: false
    pair_ff_expand: 4
    tri_mul: true
    rope: true

    ### ipa args
    # translation equivariant
    move_x_to_xcond: true
    readout_trans_before_sm: false
    ipa_relpos: true
    ipa_frame_update: true
    zero_frames_before_ipa: true
    zero_x_before_ipa: false
    
    ipa_blocks: 8    
    separate_ipa_blocks: false
    
    embed_trans: false
    ipa_pair_values: false
    ipa_pair_bias: true
    detach_rots: true
    detach_trans: true
    detach_x: false
    trunk_adaLN: true
    sm_adaLN: true


optimizer:
    type: AdamW
    lr: 5e-4
    scheduler: 
        total_steps: 1000000
        warmup_steps: 1000
        start_decay: 10000
        end_factor: 1.00
        