ckpt: null
pretrained: null # workdir/trimul-vanilla-disto/last.ckpt # workdir/nodiff-relpos-pade/last.ckpt # load weights from here first
validate: false # if true, only validate the model, don't train
logger:
    # set to true to log to neptune.ai
    neptune: true
    run_id: null  
    # please change "test" to something unique to your task
    project: openprot/diffusion
    # will log to workdir and neptune.ai with this name
    name: struct-gen-notri-edm-align # struct-gen-notri-gaussianfm+pdb
    # if not null, will duplicate stdout and stderr to workdir/{name}/{logfile}
    logfile: std.out
    # if null, will log every epoch, otherwise every this number of steps
    train_log_freq: 10
    val_log_freq: null 
    ckpt_freq: 10000000
    save_freq: 5000
trainer:
    accelerator: auto
    devices: 1
    max_epochs: 1
    max_steps: 1000000
    enable_progress_bar: true
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    num_sanity_val_steps: 0
    gradient_clip_val: 1.0
    accumulate_grad_batches: 1
    val_check_interval: 5000
    check_val_every_n_epoch: 1
    logger: false

# custom args to OpenProtDataset and elsewhere
data: 
    num_workers: 32
    batch: 32
    crop: 256
    seed: 137

# These are the raw features which are expected to be supplied by the Datasets
# before they are TOKENIZED by the Tracks.
# We specify them and their shapes so that datasets can supply default values if missing
# for example, a structure dataset will not supply any dynamics information.
# We also need to set defaults for the "mask" and "noise" because not all Tasks will set them.
# -1 means this is the LEGNTH dim. 
features:
    # sequence feats
    seq_mask: [-1]
    seq_noise: [-1]
    # structure feats are unconventional
    # because they really mix 3 modalities
    atom37: [-1, 37, 3]
    atom37_mask: [-1, 37]
    trans_noise: [-1]
    rots_noise: [-1]
    # torsion_noise: [-1]
datasets:
    pdb:
        type: PDBDataset
        path: /scratch/projects/cgai/openprot/data/pdb_npz
        cutoff: 2018-05-01
        clusters: /scratch/projects/cgai/openprot/data/pdb_clusters
        blacklist: /scratch/projects/cgai/openprot/cameo_pdb_blacklist.tsv
    afdb_genie:
        type: AFDBDataset
        path: /scratch/projects/cgai/openprot/data/afdb_rep_v4/afdb_rep_v4
        annotations: /scratch/projects/cgai/openprot/data/afdb_rep_v4.pkl.gz
        blacklist: null 
        plddt_thresh: null 
        index: /scratch/projects/cgai/openprot/afdbreps_l-256_plddt_80.txt

            
tasks:
    StructureGeneration:
        fraction: 1.0
        beta: [1, 2]
        uniform_prob: 0.5
        max_noise_prob: 0.0
        seed: 137
        random_rot: true
        datasets:
            afdb_genie:
                fraction: 0.75
                start: 0
                seed: 142
            pdb:
                fraction: 0.25
                start: 0
                seed: 142
evals:
    struct_gen_sde_0.5:
        type: StructureGenerationEval
        num_samples: 100
        sample_length: 128
        nsteps: 200
        sched_type: 'log'
        sde_weight: 10.0
        temp_factor: 0.5
        sde_cutoff_time: 0.0
        sde_cutoff_width: 0.00001
        run_designability: true
    struct_gen_sde_0.7:
        type: StructureGenerationEval
        num_samples: 100
        sample_length: 128
        nsteps: 200
        sched_type: 'log'
        sde_weight: 10.0
        temp_factor: 0.7
        sde_cutoff_time: 0.0
        sde_cutoff_width: 0.00001
        run_designability: true
    struct_gen_sde_1.0:
        type: StructureGenerationEval
        num_samples: 100
        sample_length: 128
        nsteps: 200
        sched_type: 'log'
        sde_weight: 10.0
        temp_factor: 1.0
        sde_cutoff_time: 0.0
        sde_cutoff_width: 0.00001
        run_designability: true
    

tracks:
    # register tracks here
    StructureTrack: 
        loss_weight: 1.0
        readout_pairwise: false
        
        embed_trans: edm
        readout_trans: true
        int_loss_weight: 0.0
        
        rot_augment: 1
        embed_pairwise: false
        struct_module: false
        
        clamp_pade: false
        clamp_nape: true
        clamp_mse: false
        nape_cutoff: 15
        losses:
            diffusion: 1.0
        diffusion:
            # type: GaussianFM
            # prior_sigma: 15.0
            # center_noise: true
            # center_pos: true
            # train_align: false
            # inf_align: false
            # prediction: "velocity"
            type: EDMDiffusion
            sched_p: 7
            data_sigma: 15
            sigma_max: 160
            sigma_min: 0.05
            aligned_loss: true
    SequenceTrack:
        esm: null # esm2_3B # esm2_650M # esm2_8M_270K
        corrupt: mask
        mask_rate: 0.0
        loss_weight: 0.0

model: # custom args
    checkpoint: false
    dim: 1024
    pairwise_dim: 128
    heads: 16
    pairwise_heads: 4
    blocks: 12
    
    # topology of the network
    pair_blocks:
        start: 0
        end: 0
        interval: 1
    struct_module: false
    sm_block_idx: 12
    
    pairwise_pos_emb: false
    
    ff_expand: 4
    position_bins: 32
    pair_ffn: true
    pair_values: false
    pair_bias: true
    pair_ff_expand: 4
    tri_mul: false
    rope: true

    ### ipa args

    zero_frames_before_ipa: false
    
    ipa_blocks: 8
    separate_ipa_blocks: false
    ipa_pair_values: false
    ipa_pair_bias: true
    detach_rots: true
    detach_trans: true
    trunk_adaLN: true
    sm_adaLN: true


optimizer:
    type: AdamW
    lr: 1e-4
    scheduler: 
        total_steps: 1000000
        warmup_steps: 1000
        start_decay: 10000
        end_factor: 1.00
        