ckpt: null # workdir/struct-gen-notri-edm-sm/last.ckpt
pretrained: null # workdir/trimul-vanilla-disto/last.ckpt # workdir/nodiff-relpos-pade/last.ckpt # load weights from here first
validate: false # if true, only validate the model, don't train
logger:
    # set to true to log to neptune.ai
    neptune: true
    run_id: null # DIF-106  
    # please change "test" to something unique to your task
    project: openprot/diffusion
    # will log to workdir and neptune.ai with this name
    name: struct-gen-notri-relpos-1000 # struct-gen-notri-gaussianfm+pdb
    # if not null, will duplicate stdout and stderr to workdir/{name}/{logfile}
    logfile: std.out
    # if null, will log every epoch, otherwise every this number of steps
    train_log_freq: 10
    val_log_freq: null 
    ckpt_freq: 10000000
    save_freq: 5000
trainer:
    accelerator: auto
    devices: 1
    max_epochs: 1
    max_steps: 1000000
    enable_progress_bar: true
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    num_sanity_val_steps: 0
    gradient_clip_val: 1.0
    accumulate_grad_batches: 1
    val_check_interval: 5000
    check_val_every_n_epoch: 1
    logger: false

# custom args to OpenProtDataset and elsewhere
data: 
    num_workers: 32
    batch: 32
    crop: 256
    seed: 137

# These are the raw features which are expected to be supplied by the Datasets
# before they are TOKENIZED by the Tracks.
# We specify them and their shapes so that datasets can supply default values if missing
# for example, a structure dataset will not supply any dynamics information.
# We also need to set defaults for the "mask" and "noise" because not all Tasks will set them.
# -1 means this is the LEGNTH dim. 
features:
    # sequence feats
    seq_mask: [-1]
    seq_noise: [-1]
    # structure feats are unconventional
    # because they really mix 3 modalities
    atom37: [-1, 37, 3]
    atom37_mask: [-1, 37]
    trans_noise: [-1]
    rots_noise: [-1]
    # torsion_noise: [-1]
datasets:
    pdb:
        type: PDBDataset
        path: /scratch/projects/cgai/openprot/data/pdb_npz
        cutoff: 2018-05-01
        clusters: /scratch/projects/cgai/openprot/data/pdb_clusters
        blacklist: /scratch/projects/cgai/openprot/cameo_pdb_blacklist.tsv
    afdb_genie:
        type: AFDBDataset
        path: /scratch/projects/cgai/openprot/data/afdb_rep_v4/afdb_rep_v4
        annotations: /scratch/projects/cgai/openprot/data/afdb_rep_v4.pkl.gz
        blacklist: null 
        plddt_thresh: null 
        index: /scratch/projects/cgai/openprot/afdbreps_l-256_plddt_80.txt

            
tasks:
    StructureGeneration:
        fraction: 1.0
        beta: [1, 2]
        uniform_prob: 0.5
        max_noise_prob: 0.0
        seed: 137
        random_rot: true
        sched_p: 7
        sigma_max: 160
        sigma_min: 0.05
        datasets:
            afdb_genie:
                fraction: 0.75
                start: 0
                seed: 142
            pdb:
                fraction: 0.25
                start: 0
                seed: 142
evals:
    struct_gen_sde_0.5:
        type: StructureGenerationEval
        num_samples: 100
        sample_length: 128
        nsteps: 200
        sched_p: 7
        sigma_max: 160
        sigma_min: 0.05
        temp_factor: 0.5
        run_designability: true
    struct_gen_sde_0.7:
        type: StructureGenerationEval
        num_samples: 100
        sample_length: 128
        nsteps: 200
        sched_p: 7
        sigma_max: 160
        sigma_min: 0.05
        temp_factor: 0.7
        run_designability: true
    struct_gen_sde_1.0:
        type: StructureGenerationEval
        num_samples: 100
        sample_length: 128
        nsteps: 200
        sched_p: 7
        sigma_max: 160
        sigma_min: 0.05
        temp_factor: 1.0
        run_designability: true
    

tracks:
    # register tracks here
    StructureTrack: 
        loss_weight: 1.0
        readout_pairwise: false
        embed_trans: null
        # trunk or sm
        readout_trans: null
        postcondition: true
        int_loss_weight: 0.5
        t_emb_p: 7
        t_emb_max: 160
        t_emb_min: 0.05
        embed_pairwise: false
        
        nape_cutoff: 15
        losses:
            lddt: 1.0
            mse: 0.225
        diffusion:
            type: EDMDiffusion
            data_sigma: 15
            aligned_loss: true
    SequenceTrack:
        esm: null # esm2_3B # esm2_650M # esm2_8M_270K
        loss_weight: 0.0
        embed_t: false
        loss_reweight: var

model: # custom args
    checkpoint: false
    dim: 1024
    pairwise_dim: 128
    heads: 16
    pairwise_heads: 4
    blocks: 12

    relpos: true
    trunk_relpos: [32, 1, 1000]
    sm_relpos: [32, 1, 100]
    # topology of the network
    pair_blocks:
        start: 0
        end: 0
        interval: 1
    struct_module: true
    sm_block_idx: 12
    
    pairwise_pos_emb: false
    block_pair_bias: false
    ff_expand: 4
    position_bins: 32
    pair_ffn: true
    pair_values: false
    pair_bias: true
    pair_ff_expand: 4
    tri_mul: false
    rope: false
    custom_rope: true

    ### ipa args
    readout_trans_before_sm: false
    zero_frames_before_ipa: true
    
    ipa_blocks: 8
    separate_ipa_blocks: false
    ipa_pair_values: false
    ipa_pair_bias: false
    embed_trans: false
    detach_rots: true
    detach_trans: true
    detach_x: false
    trunk_adaLN: true
    sm_adaLN: true
    readout_adaLN: true
    
    move_x_to_xcond: true
    ipa_relpos: true
    ipa_nipa: false
    ipa_rope: false
    ipa_frame_update: true
    zero_x_before_ipa: false
    
optimizer:
    type: AdamW
    lr: 1e-4
    # betas: [0.9, 0.98]
    # eps: 1e-8
    # weight_decay: 0.01
    # fused: true
    scheduler: 
        total_steps: 1000000
        warmup_steps: 1000
        start_decay: 10000
        end_factor: 1.00
        